import { Mp3Encoder } from '@breezystack/lamejs';

/**
 * WAV file encoding and PCM manipulation utilities
 * Supports 24kHz 16-bit mono audio generated by Gemini TTS and MP3 export
 */

export function pcmToWavBuffer(
  pcmData: Buffer | Uint8Array,
  sampleRate = 24000,
  numChannels = 1,
  bitsPerSample = 16
): Buffer {
  const byteRate = sampleRate * numChannels * (bitsPerSample / 8);
  const blockAlign = numChannels * (bitsPerSample / 8);
  const dataSize = pcmData.length;
  const buffer = Buffer.alloc(44 + dataSize);

  // RIFF chunk descriptor
  buffer.write('RIFF', 0);
  buffer.writeUInt32LE(36 + dataSize, 4);
  buffer.write('WAVE', 8);

  // "fmt " sub-chunk
  buffer.write('fmt ', 12);
  buffer.writeUInt32LE(16, 16); // Subchunk1Size for PCM
  buffer.writeUInt16LE(1, 20); // AudioFormat (1 = PCM)
  buffer.writeUInt16LE(numChannels, 22);
  buffer.writeUInt32LE(sampleRate, 24);
  buffer.writeUInt32LE(byteRate, 28);
  buffer.writeUInt16LE(blockAlign, 32);
  buffer.writeUInt16LE(bitsPerSample, 34);

  // "data" sub-chunk
  buffer.write('data', 36);
  buffer.writeUInt32LE(dataSize, 40);

  // Copy PCM samples
  if (Buffer.isBuffer(pcmData)) {
    pcmData.copy(buffer, 44);
  } else {
    Buffer.from(pcmData).copy(buffer, 44);
  }

  return buffer;
}

/**
 * Client-side conversion of AudioBuffer to a downloadable WAV Blob
 */
export function audioBufferToWavBlob(buffer: AudioBuffer): Blob {
  const numChannels = buffer.numberOfChannels;
  const sampleRate = buffer.sampleRate;
  const format = 1; // PCM
  const bitDepth = 16;

  let result: Float32Array;
  if (numChannels === 2) {
    const left = buffer.getChannelData(0);
    const right = buffer.getChannelData(1);
    result = new Float32Array(left.length + right.length);
    for (let i = 0; i < left.length; i++) {
      result[i * 2] = left[i];
      result[i * 2 + 1] = right[i];
    }
  } else {
    result = buffer.getChannelData(0);
  }

  const bytesPerSample = bitDepth / 8;
  const blockAlign = numChannels * bytesPerSample;
  const dataByteLength = result.length * bytesPerSample;
  const arrayBuffer = new ArrayBuffer(44 + dataByteLength);
  const view = new DataView(arrayBuffer);

  // Write RIFF identifier
  writeString(view, 0, 'RIFF');
  // File length minus 8 bytes RIFF descriptor
  view.setUint32(4, 36 + dataByteLength, true);
  // RIFF type
  writeString(view, 8, 'WAVE');
  // Format chunk identifier
  writeString(view, 12, 'fmt ');
  // Format chunk length
  view.setUint32(16, 16, true);
  // Sample format (raw)
  view.setUint16(20, format, true);
  // Channel count
  view.setUint16(22, numChannels, true);
  // Sample rate
  view.setUint32(24, sampleRate, true);
  // Byte rate (sample rate * block align)
  view.setUint32(28, sampleRate * blockAlign, true);
  // Block align
  view.setUint16(32, blockAlign, true);
  // Bits per sample
  view.setUint16(34, bitDepth, true);
  // Data chunk identifier
  writeString(view, 36, 'data');
  // Data chunk length
  view.setUint32(40, dataByteLength, true);

  // Write interleaved PCM samples
  let offset = 44;
  for (let i = 0; i < result.length; i++) {
    const s = Math.max(-1, Math.min(1, result[i]));
    const intSample = s < 0 ? s * 0x8000 : s * 0x7fff;
    view.setInt16(offset, intSample, true);
    offset += 2;
  }

  return new Blob([arrayBuffer], { type: 'audio/wav' });
}

/**
 * Encodes an AudioBuffer into high quality MP3 Blob (192 kbps)
 */
export function audioBufferToMp3Blob(audioBuffer: AudioBuffer, kbps = 192): Blob {
  const channels = audioBuffer.numberOfChannels;
  const sampleRate = audioBuffer.sampleRate;
  const encoder = new Mp3Encoder(channels, sampleRate, kbps);
  const mp3Data: Uint8Array[] = [];

  const left = audioBuffer.getChannelData(0);
  const right = channels > 1 ? audioBuffer.getChannelData(1) : undefined;

  const sampleBlockSize = 1152;
  const numSamples = left.length;

  for (let i = 0; i < numSamples; i += sampleBlockSize) {
    const chunkLength = Math.min(sampleBlockSize, numSamples - i);
    const leftChunk = new Int16Array(chunkLength);
    for (let j = 0; j < chunkLength; j++) {
      const s = Math.max(-1, Math.min(1, left[i + j]));
      leftChunk[j] = s < 0 ? s * 0x8000 : s * 0x7fff;
    }

    let mp3buf: Uint8Array;
    if (right) {
      const rightChunk = new Int16Array(chunkLength);
      for (let j = 0; j < chunkLength; j++) {
        const s = Math.max(-1, Math.min(1, right[i + j]));
        rightChunk[j] = s < 0 ? s * 0x8000 : s * 0x7fff;
      }
      mp3buf = encoder.encodeBuffer(leftChunk, rightChunk);
    } else {
      mp3buf = encoder.encodeBuffer(leftChunk);
    }

    if (mp3buf.length > 0) {
      mp3Data.push(mp3buf);
    }
  }

  const endChunk = encoder.flush();
  if (endChunk.length > 0) {
    mp3Data.push(endChunk);
  }

  return new Blob(mp3Data as BlobPart[], { type: 'audio/mp3' });
}

/**
 * Converts a WAV Blob into an MP3 Blob using Web Audio decoding
 */
export async function wavBlobToMp3Blob(wavBlob: Blob, kbps = 192): Promise<Blob> {
  const arrayBuffer = await wavBlob.arrayBuffer();
  const AudioCtxClass =
    window.AudioContext ||
    (window as unknown as { webkitAudioContext: typeof AudioContext }).webkitAudioContext;
  const audioCtx = new AudioCtxClass();
  const audioBuffer = await audioCtx.decodeAudioData(arrayBuffer);
  const mp3Blob = audioBufferToMp3Blob(audioBuffer, kbps);
  await audioCtx.close();
  return mp3Blob;
}

function writeString(view: DataView, offset: number, string: string) {
  for (let i = 0; i < string.length; i++) {
    view.setUint8(offset + i, string.charCodeAt(i));
  }
}

